### ISSUE TITLE
Fatal TypeError: Error during conversion: oldType.trim is not a function

### ISSUE THREAD

**Issue by ianfixes** [apigee-127/swagger-converter#82]
Originally https://github.com/LucyBot-Inc/api-spec-converter/issues/212

 I'm attempting to convert `https://api.newrelic.com/v2/definitions.json` to Swagger 2 (or higher).  

Steps to reproduce:

```shell
$ npm install -s api-spec-converter
/home/me/newrelic
└── api-spec-converter@2.8.3 

$ ./node_modules/.bin/api-spec-converter -f swagger_1 -t swagger_2 -s json https://api.newrelic.com/v2/definitions.json 
Fatal TypeError: Error during conversion: oldType.trim is not a function
    at Converter.prototype.buildTypeProperties (/home/me/newrelic/node_modules/swagger-converter/index.js:340:21)
    at Converter.prototype.buildDataType (/home/me/newrelic/node_modules/swagger-converter/index.js:430:21)
    at Converter.prototype.buildModel (/home/me/newrelic/node_modules/swagger-converter/index.js:760:22)
    at Converter.prototype.buildModel (/home/me/newrelic/node_modules/swagger-converter/index.js:757:18)
    at Converter.<anonymous> (/home/me/newrelic/node_modules/swagger-converter/index.js:749:37)
    at /home/me/newrelic/node_modules/swagger-converter/index.js:842:7
    at Array.forEach (native)
    at Converter.prototype.forEach (/home/me/newrelic/node_modules/swagger-converter/index.js:841:36)
    at Converter.prototype.buildModel (/home/me/newrelic/node_modules/swagger-converter/index.js:744:8)
    at Converter.<anonymous> (/home/me/newrelic/node_modules/swagger-converter/index.js:782:28)
    at /home/me/newrelic/node_modules/swagger-converter/index.js:842:7
    at Array.forEach (native)
    at Converter.prototype.forEach (/home/me/newrelic/node_modules/swagger-converter/index.js:841:36)
    at Converter.prototype.buildDefinitions (/home/me/newrelic/node_modules/swagger-converter/index.js:781:8)
    at Converter.<anonymous> (/home/me/newrelic/node_modules/swagger-converter/index.js:142:30)
    at Array.forEach (native)
```

It was [suggested](https://github.com/LucyBot-Inc/api-spec-converter/issues/212#issuecomment-489236023) that 
> you've got something weird in one of your types, like an object or an array. Not sure if arrays were allowed in Swagger 1

However, the spec in question is being used to generate [NewRelic's docs](https://rpm.newrelic.com/api/explore/) using what appears to be [the official SwaggerUI](https://github.com/swagger-api/swagger-ui).  So I assume the spec is at least reasonable.  Is there anything I can do to work around this?

**Comment by IvanGoncharov** [comment]
@ianfixes Thanks for reporting and sorry for the late response.
Sadly it bug in New Relic spec they basically have incorrect `$ref`:
```js
{
  '$ref': {
    duration: 'string',
    operator: 'string',
    priority: 'string',
    threshold: 'string',
    time_function: 'string'
  }
}
```

**Comment by ianfixes** [comment]
Thanks for getting back to me, and no worries about the time delay.  The time to beat is my bug report in the Thunderbird mail client that got its first response after 11 years 😅   

Can you point me to the docs about whatever makes that `$ref` incorrect?  It sounds like the issue there is immediately obvious to you, but it's over my head.  I'd like to read up on that if I can.

**Comment by IvanGoncharov** [comment]
@ianfixes Original docs accessible only through web cache:
http://webcache.googleusercontent.com/search?q=cache:nEcSVhz7OgwJ:https://docs.swagger.io/spec.html&hl=en&gl=ua&strip=1&vwsrc=0
Search for `$ref` and you will find this:
![image](https://user-images.githubusercontent.com/8336157/100965662-d3ec1200-3533-11eb-9f7c-214d22fe9f34.png)
More generically `$ref` described here:
https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#:~:text=A%20JSON%20Reference%20is%20a,interpreted%20as%20a%20JSON%20Reference.
